### ISSUE TITLE
Cant turn On

### ISSUE THREAD

**Issue by emilsvfx** [leomoon-studios/leomoon-lightstudio#10]
Traceback (most recent call last):
  File "C:\Users\Emilsvfx\Desktop\devbuild-03-09-2018\Release\2.79\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Emilsvfx\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\blender-light-studio\__init__.py", line 38, in <module>
    modules = developer_utils.setup_addon_modules(__path__, __name__, "bpy" in locals())
  File "C:\Users\Emilsvfx\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\blender-light-studio\developer_utils.py", line 35, in setup_addon_modules
    modules = import_submodules(names)
  File "C:\Users\Emilsvfx\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\blender-light-studio\developer_utils.py", line 27, in import_submodules
    modules.append(importlib.import_module("." + name, package_name))
  File "C:\Users\Emilsvfx\Desktop\devbuild-03-09-2018\Release\2.79\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Emilsvfx\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\blender-light-studio\gui.py", line 151, in <module>
    from extensions_framework import util as efutil
ImportError: cannot import name 'util' from 'extensions_framework' (unknown location)

**Comment by leomoon** [comment]
Hello,
Please download [THIS](https://filedn.com/lySwaAnkmuoJtXuM6Dq7AmF/extensions_framework.zip) and extract the “extensions_framework” to:
BLENDER_SETUP_DIRECTORY/2.79/scripts/addons/modules/

**Comment by emilsvfx** [comment]
wow. super tnx :)

[image: photo]
*Emīls Geršinskis* - *Ješinskis*
CG | VFX | Designer
w:http://www.emilsvfx.lv
<http://www.facebook.com/emilsvfx>  <http://twitter.com/emilsvfx>
<http://vimeo.com/user3392316>  <https://www.instagram.com/emilsvfx/>
<https://www.youtube.com/channel/UCijGkeuwfVMjNmKyj7Z9KtA>
