### ISSUE TITLE
Basic light issues

### ISSUE THREAD

**Issue by leomoon** [leomoon-studios/leomoon-lightstudio#46]
Selecting basic lights will give this error:
```
Traceback (most recent call last):
  File "C:\Users\LeoMoon\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\leomoon-lightstudio-master\light_operators.py", line 428, in msgbus_callback
    light_group_list = [n for n in active_object.active_material.node_tree.nodes if n.name.startswith('Group')]
AttributeError: 'NoneType' object has no attribute 'node_tree'
File "C:\Users\LeoMoon\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\leomoon-lightstudio-master\light_operators.py", line 411, in msgbus_callback
Traceback (most recent call last):
  File "C:\Users\LeoMoon\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\leomoon-lightstudio-master\light_operators.py", line 428, in msgbus_callback
    light_group_list = [n for n in active_object.active_material.node_tree.nodes if n.name.startswith('Group')]
AttributeError: 'NoneType' object has no attribute 'node_tree'
File "C:\Users\LeoMoon\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\leomoon-lightstudio-master\light_operators.py", line 411, in msgbus_callback
```
Also switching a basic light from Normal to Animation then back to Normal has strange behavior.

**Comment by leomoon** [comment]
fixed in 2.8.2
